name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          cd starter/backend
          pip install -r requirements.txt
          pip install pylint
      
      - name: Run Linter
        run: |
          cd starter/backend
          pylint $(git ls-files '*.py')

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          cd starter/backend
          pip install -r requirements.txt
          pip install pytest
      
      - name: Run Tests
        run: |
          cd starter/backend
          pytest

  build:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: |
          cd starter/backend
          docker build -t backend-app .