name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

env:
    REACT_APP_MOVIE_API_URL: http://localhost:5000

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:	      
          node-version: '18.14'
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json	      
      
      - name: Install Dependencies
        run: |
          cd starter/frontend
          npm ci 
      
      - name: Run Linter
        run: |
          cd starter/frontend
          npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: starter/frontend/package-lock.json
          node-version: '18.14'
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          cd starter/frontend
          npm ci 
      
      - name: Run Tests
        run: |
          cd starter/frontend
          CI=true npm test

  build:
    name: Build Docker Image Frontend
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
           
      - name: Build Docker Image with Build Args
        run: |
          cd starter/frontend
          docker build --build-arg REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL -t frontend-app .
